import { useState } from 'react'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { api } from '../api/client'
import type { ValidationItem } from '../types'
import {
  ClipboardCheck,
  CheckCircle2,
  XCircle,
  AlertTriangle,
  SkipForward,
  Loader2,
  ChevronDown,
  ChevronUp,
  Sparkles,
  Eye,
  Check,
  X,
} from 'lucide-react'

const priorityColors: Record<number, { bg: string; text: string; label: string }> = {
  1: { bg: 'bg-red-100', text: 'text-red-800', label: 'P1 · Critical' },
  2: { bg: 'bg-orange-100', text: 'text-orange-800', label: 'P2 · High' },
  3: { bg: 'bg-yellow-100', text: 'text-yellow-800', label: 'P3 · Medium' },
  4: { bg: 'bg-blue-100', text: 'text-blue-800', label: 'P4 · Low' },
  5: { bg: 'bg-gray-100', text: 'text-gray-800', label: 'P5 · Info' },
}

export default function ValidationQueue() {
  const [page, setPage] = useState(1)
  const [actionLoading, setActionLoading] = useState<string | null>(null)
  const [expandedId, setExpandedId] = useState<string | null>(null)
  const [selectedItem, setSelectedItem] = useState<ValidationItem | null>(null)
  const queryClient = useQueryClient()

  const { data: queue, isLoading } = useQuery({
    queryKey: ['validation-queue', page],
    queryFn: async () => {
      const { data } = await api.get<{ items: ValidationItem[] }>('/validation/queue', {
        params: { page, page_size: 20, status: 'pending' },
      })
      return data
    },
    refetchInterval: 5000,
  })

  const applyAction = useMutation({
    mutationFn: async ({ id, action }: { id: string; action: string }) => {
      const { data } = await api.post(`/validation/${id}/action`, {
        action,
        reviewer_id: 'demo-user',
      })
      return data
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['validation-queue'] })
      queryClient.invalidateQueries({ queryKey: ['dashboard-stats'] })
      queryClient.invalidateQueries({ queryKey: ['products'] })
      setSelectedItem(null)
    },
  })

  const handleAction = async (id: string, action: string) => {
    setActionLoading(id)
    try {
      await applyAction.mutateAsync({ id, action })
    } finally {
      setActionLoading(null)
    }
  }

  const formatProposedValue = (val: string) => {
    try {
      const parsed = JSON.parse(val)
      if (typeof parsed === 'object' && parsed !== null) {
        return (
          <div className="space-y-1 mt-1">
            {Object.entries(parsed).map(([k, v]) => (
              <div key={k} className="text-xs flex gap-2">
                <span className="font-semibold text-gray-700 capitalize">{k.replace(/_/g, ' ')}:</span>
                <span className="text-blue-900">{typeof v === 'object' ? JSON.stringify(v) : String(v)}</span>
              </div>
            ))}
          </div>
        )
      }
    } catch {
      // Plain text
    }
    return <p className="text-sm text-gray-800 whitespace-pre-wrap leading-relaxed">{val}</p>
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Human-in-the-Loop Validation</h1>
          <p className="text-gray-500 mt-1">
            Review and approve technical descriptions, specs, and changes generated by Google Gemini AI
          </p>
        </div>
        <div className="flex items-center gap-2">
          <span className="px-3 py-1 bg-blue-50 border border-blue-200 text-blue-800 rounded-full text-xs font-semibold">
            {queue?.items?.length || 0} Pending Reviews
          </span>
        </div>
      </div>

      {/* Cards View */}
      <div className="space-y-4">
        {queue?.items.map((item) => {
          const isExpanded = expandedId === item.id
          const pInfo = priorityColors[item.priority] || priorityColors[5]
          const isLoadingThis = actionLoading === item.id

          return (
            <div
              key={item.id}
              className={`card border transition-all ${
                isExpanded ? 'border-blue-300 shadow-md ring-1 ring-blue-100' : 'border-gray-200 hover:border-gray-300'
              }`}
            >
              {/* Header row */}
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-3 border-b border-gray-100">
                <div className="flex items-center gap-3">
                  <span className={`px-2.5 py-0.5 rounded-full text-xs font-medium ${pInfo.bg} ${pInfo.text}`}>
                    {pInfo.label}
                  </span>
                  <div>
                    <h3 className="text-base font-semibold text-gray-900 flex items-center gap-2">
                      {item.field_name}
                      <span className="text-xs font-normal text-gray-400 font-mono">
                        (Path: {item.field_path})
                      </span>
                    </h3>
                  </div>
                </div>

                <div className="flex items-center gap-3">
                  <div className="flex items-center gap-1.5 px-2.5 py-1 bg-purple-50 text-purple-700 rounded-md text-xs font-medium">
                    <Sparkles className="w-3.5 h-3.5" />
                    <span>AI Confidence: {((item.ai_confidence || 0) * 100).toFixed(0)}%</span>
                  </div>

                  <div className="flex items-center gap-2">
                    <button
                      className="btn-primary py-1.5 px-3 text-xs flex items-center gap-1.5 bg-green-600 hover:bg-green-700"
                      onClick={() => handleAction(item.id, 'approve')}
                      disabled={isLoadingThis}
                    >
                      {isLoadingThis ? (
                        <Loader2 className="w-3.5 h-3.5 animate-spin" />
                      ) : (
                        <Check className="w-3.5 h-3.5" />
                      )}
                      Approve & Save
                    </button>

                    <button
                      className="btn-secondary py-1.5 px-3 text-xs flex items-center gap-1.5 text-red-600 border-red-200 hover:bg-red-50"
                      onClick={() => handleAction(item.id, 'reject')}
                      disabled={isLoadingThis}
                    >
                      <X className="w-3.5 h-3.5" />
                      Reject
                    </button>

                    <button
                      onClick={() => setExpandedId(isExpanded ? null : item.id)}
                      className="p-1.5 text-gray-400 hover:text-gray-600 rounded-lg hover:bg-gray-100"
                      title={isExpanded ? "Collapse" : "Expand Details"}
                    >
                      {isExpanded ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4" />}
                    </button>
                  </div>
                </div>
              </div>

              {/* Main Diff Content */}
              <div className="grid grid-cols-1 lg:grid-cols-2 gap-4 pt-3">
                {/* Left: Original Value */}
                <div className="bg-gray-50 p-3.5 rounded-lg border border-gray-200">
                  <p className="text-xs font-semibold text-gray-500 uppercase tracking-wider mb-1.5">
                    Original / Current Value
                  </p>
                  {item.old_value ? (
                    <p className="text-sm text-gray-700 whitespace-pre-wrap leading-relaxed">{item.old_value}</p>
                  ) : (
                    <span className="text-xs text-gray-400 italic font-mono bg-white px-2 py-1 rounded border border-gray-200 inline-block">
                      [EMPTY / NOT SET]
                    </span>
                  )}
                </div>

                {/* Right: Gemini Proposed Value */}
                <div className="bg-blue-50/60 p-3.5 rounded-lg border border-blue-200">
                  <div className="flex items-center justify-between mb-1.5">
                    <p className="text-xs font-semibold text-blue-900 uppercase tracking-wider flex items-center gap-1">
                      <Sparkles className="w-3.5 h-3.5 text-blue-600" />
                      Gemini Proposed Enrichment
                    </p>
                  </div>
                  <div className="text-sm text-gray-900 leading-relaxed max-h-96 overflow-y-auto">
                    {formatProposedValue(item.proposed_value)}
                  </div>
                </div>
              </div>

              {/* AI Reasoning Footer */}
              {item.ai_reasoning && (
                <div className="mt-3 pt-2.5 border-t border-gray-100 flex items-start gap-2 text-xs text-gray-600 bg-amber-50/60 p-2.5 rounded border border-amber-200">
                  <span className="font-semibold text-amber-900 flex-shrink-0">🤖 Gemini Rationale:</span>
                  <span className="text-amber-950 leading-normal">{item.ai_reasoning}</span>
                </div>
              )}
            </div>
          )
        })}

        {(!queue?.items || queue.items.length === 0) && (
          <div className="card py-16 text-center text-gray-500">
            <ClipboardCheck className="w-16 h-16 mx-auto mb-4 text-green-400" />
            <h3 className="text-lg font-bold text-gray-800">All Caught Up!</h3>
            <p className="text-sm text-gray-500 mt-1 max-w-md mx-auto">
              There are no pending validation items. Go to Products or Documents to enrich items and generate new validation proposals.
            </p>
          </div>
        )}
      </div>
    </div>
  )
}
