import { useState } from 'react'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { motion, AnimatePresence } from 'framer-motion'
import { api } from '../api/client'
import type { ValidationItem } from '../types'
import {
  ClipboardCheck,
  Loader2,
  ChevronDown,
  ChevronUp,
  Sparkles,
  Check,
  X,
  Zap,
} from 'lucide-react'

const priorityColors: Record<number, { bg: string; text: string; label: string; shadow: string }> = {
  1: { bg: 'bg-red-500/20 border-red-500/30', text: 'text-red-400', label: 'P1 · Critical', shadow: 'shadow-[0_0_10px_rgba(239,68,68,0.2)]' },
  2: { bg: 'bg-orange-500/20 border-orange-500/30', text: 'text-orange-400', label: 'P2 · High', shadow: 'shadow-[0_0_10px_rgba(249,115,22,0.2)]' },
  3: { bg: 'bg-yellow-500/20 border-yellow-500/30', text: 'text-yellow-400', label: 'P3 · Medium', shadow: 'shadow-[0_0_10px_rgba(234,179,8,0.2)]' },
  4: { bg: 'bg-blue-500/20 border-blue-500/30', text: 'text-blue-400', label: 'P4 · Low', shadow: 'shadow-[0_0_10px_rgba(59,130,246,0.2)]' },
  5: { bg: 'bg-white/5 border-white/10', text: 'text-white/60', label: 'P5 · Info', shadow: 'shadow-inner' },
}

export default function ValidationQueue() {
  const [page] = useState(1)
  const [actionLoading, setActionLoading] = useState<string | null>(null)
  const [expandedId, setExpandedId] = useState<string | null>(null)
  const queryClient = useQueryClient()

  const { data: queue } = useQuery({
    queryKey: ['validation-queue', page],
    queryFn: async () => {
      const { data } = await api.get<{ items: ValidationItem[] }>('/validation/queue', {
        params: { page, page_size: 20, status: 'pending' },
      })
      return data
    },
    refetchInterval: 5000,
  })

  const applyAction = useMutation({
    mutationFn: async ({ id, action }: { id: string; action: string }) => {
      const { data } = await api.post(`/validation/${id}/action`, {
        action,
        reviewer_id: 'demo-user',
      })
      return data
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['validation-queue'] })
      queryClient.invalidateQueries({ queryKey: ['dashboard-stats'] })
      queryClient.invalidateQueries({ queryKey: ['products'] })
    },
  })

  const handleAction = async (id: string, action: string) => {
    setActionLoading(id)
    try {
      await applyAction.mutateAsync({ id, action })
    } finally {
      setActionLoading(null)
    }
  }

  const formatProposedValue = (val: string) => {
    try {
      const parsed = JSON.parse(val)
      if (typeof parsed === 'object' && parsed !== null) {
        return (
          <div className="space-y-2 mt-2 bg-dark-800/50 p-4 rounded-xl border border-white/5">
            {Object.entries(parsed).map(([k, v]) => (
              <div key={k} className="text-sm flex gap-3 pb-1 border-b border-white/5 last:border-0">
                <span className="font-bold text-white/50 capitalize w-1/3">{k.replace(/_/g, ' ')}:</span>
                <span className="text-primary-300 font-mono flex-1">{typeof v === 'object' ? JSON.stringify(v) : String(v)}</span>
              </div>
            ))}
          </div>
        )
      }
    } catch {
      // Plain text
    }
    return <p className="text-sm text-white/80 whitespace-pre-wrap leading-relaxed bg-dark-800/50 p-4 rounded-xl border border-white/5 mt-2">{val}</p>
  }

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      className="space-y-8"
    >
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-3xl font-black text-transparent bg-clip-text bg-gradient-to-r from-white via-primary-300 to-purple-400 drop-shadow-sm flex items-center gap-3">
            <ClipboardCheck className="w-8 h-8 text-primary-400" />
            Human-in-the-Loop Validation
          </h1>
          <p className="text-white/60 mt-2 font-medium">
            Review and approve technical descriptions, specs, and changes dynamically generated by Google Gemini AI
          </p>
        </div>
        <div className="flex items-center gap-2 flex-shrink-0">
          <motion.span
            animate={{ scale: [1, 1.05, 1] }}
            transition={{ duration: 2, repeat: Infinity, ease: "easeInOut" }}
            className="px-4 py-1.5 bg-primary-500/10 border border-primary-500/30 text-primary-300 rounded-full text-xs font-bold shadow-[0_0_15px_rgba(0,240,255,0.2)]"
          >
            {queue?.items?.length || 0} Pending Reviews
          </motion.span>
        </div>
      </div>

      {/* Cards View */}
      <AnimatePresence>
        <div className="space-y-6">
          {queue?.items.map((item, idx) => {
            const isExpanded = expandedId === item.id
            const pInfo = priorityColors[item.priority] || priorityColors[5]
            const isLoadingThis = actionLoading === item.id

            return (
              <motion.div
                layout
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: idx * 0.05 }}
                key={item.id}
                className={`card relative overflow-hidden transition-all duration-300 border ${
                  isExpanded ? 'border-primary-500/50 shadow-[0_0_30px_rgba(0,240,255,0.15)] bg-white/10' : 'border-white/10 hover:border-white/20 bg-dark-800/60 hover:bg-white/5'
                }`}
              >
                {/* Header row */}
                <div className="flex flex-col xl:flex-row xl:items-center justify-between gap-4 pb-4 border-b border-white/10">
                  <div className="flex items-center gap-4">
                    <span className={`px-3 py-1 rounded-md text-xs font-bold border ${pInfo.bg} ${pInfo.text} ${pInfo.shadow}`}>
                      {pInfo.label}
                    </span>
                    <div>
                      <h3 className="text-lg font-black text-white flex items-center gap-3">
                        {item.field_name}
                        <span className="text-xs font-bold text-white/40 font-mono bg-dark-800 px-2 py-1 rounded-md border border-white/5">
                          (Path: {item.field_path})
                        </span>
                      </h3>
                    </div>
                  </div>

                  <div className="flex flex-wrap items-center gap-3">
                    <div className="flex items-center gap-2 px-3 py-1.5 bg-purple-500/20 border border-purple-500/30 text-purple-300 rounded-lg text-xs font-bold shadow-[0_0_10px_rgba(168,85,247,0.2)]">
                      <Sparkles className="w-4 h-4" />
                      <span>AI Confidence: {((item.ai_confidence || 0) * 100).toFixed(0)}%</span>
                    </div>

                    <div className="flex items-center gap-2">
                      <button
                        className="px-4 py-2 text-xs font-bold flex items-center gap-2 bg-green-500/20 hover:bg-green-500/30 text-green-400 border border-green-500/30 rounded-xl transition-all shadow-[0_0_10px_rgba(34,197,94,0.2)] hover:shadow-[0_0_15px_rgba(34,197,94,0.4)] disabled:opacity-50"
                        onClick={() => handleAction(item.id, 'approve')}
                        disabled={isLoadingThis}
                      >
                        {isLoadingThis ? (
                          <Loader2 className="w-4 h-4 animate-spin" />
                        ) : (
                          <Check className="w-4 h-4" />
                        )}
                        Approve & Save
                      </button>

                      <button
                        className="px-4 py-2 text-xs font-bold flex items-center gap-2 bg-red-500/10 hover:bg-red-500/20 text-red-400 border border-red-500/20 rounded-xl transition-all hover:shadow-[0_0_10px_rgba(239,68,68,0.2)] disabled:opacity-50"
                        onClick={() => handleAction(item.id, 'reject')}
                        disabled={isLoadingThis}
                      >
                        <X className="w-4 h-4" />
                        Reject
                      </button>

                      <button
                        onClick={() => setExpandedId(isExpanded ? null : item.id)}
                        className="p-2 text-white/50 hover:text-white rounded-xl hover:bg-white/10 transition-colors border border-transparent hover:border-white/10"
                        title={isExpanded ? "Collapse" : "Expand Details"}
                      >
                        {isExpanded ? <ChevronUp className="w-5 h-5" /> : <ChevronDown className="w-5 h-5" />}
                      </button>
                    </div>
                  </div>
                </div>

                {/* Main Diff Content */}
                <AnimatePresence>
                  {isExpanded && (
                    <motion.div
                      initial={{ opacity: 0, height: 0 }}
                      animate={{ opacity: 1, height: 'auto' }}
                      exit={{ opacity: 0, height: 0 }}
                      className="grid grid-cols-1 lg:grid-cols-2 gap-6 pt-6"
                    >
                      {/* Left: Original Value */}
                      <div className="bg-dark-800/80 p-5 rounded-2xl border border-white/5 shadow-inner relative overflow-hidden">
                        <div className="absolute top-0 right-0 w-32 h-32 bg-white/5 rounded-full blur-2xl -mt-10 -mr-10 pointer-events-none" />
                        <p className="text-xs font-bold text-white/40 uppercase tracking-wider mb-4 flex items-center gap-2">
                          <span className="w-2 h-2 rounded-full bg-white/20" />
                          Original / Current Value
                        </p>
                        {item.old_value ? (
                          <p className="text-sm text-white/70 whitespace-pre-wrap leading-relaxed">{item.old_value}</p>
                        ) : (
                          <span className="text-xs text-white/30 italic font-mono bg-white/5 px-3 py-1.5 rounded-md border border-white/5 inline-block">
                            [EMPTY / NOT SET]
                          </span>
                        )}
                      </div>

                      {/* Right: Gemini Proposed Value */}
                      <div className="bg-primary-900/10 p-5 rounded-2xl border border-primary-500/20 shadow-[inset_0_0_20px_rgba(0,240,255,0.05)] relative overflow-hidden">
                        <div className="absolute top-0 right-0 w-40 h-40 bg-primary-500/10 rounded-full blur-3xl -mt-10 -mr-10 pointer-events-none" />
                        <div className="flex items-center justify-between mb-4 relative z-10">
                          <p className="text-xs font-bold text-primary-300 uppercase tracking-wider flex items-center gap-2 drop-shadow-[0_0_5px_rgba(0,240,255,0.5)]">
                            <Sparkles className="w-4 h-4 text-primary-400" />
                            Gemini Proposed Enrichment
                          </p>
                        </div>
                        <div className="text-sm text-white leading-relaxed max-h-96 overflow-y-auto relative z-10 custom-scrollbar pr-2">
                          {formatProposedValue(item.proposed_value)}
                        </div>
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>

                {/* AI Reasoning Footer */}
                <AnimatePresence>
                  {isExpanded && item.ai_reasoning && (
                    <motion.div
                      initial={{ opacity: 0 }}
                      animate={{ opacity: 1 }}
                      className="mt-6 pt-4 border-t border-white/10 flex items-start gap-3 text-sm text-white/70 bg-purple-900/20 p-4 rounded-xl border-l-4 border-l-purple-500 shadow-inner"
                    >
                      <Zap className="w-5 h-5 text-purple-400 flex-shrink-0 drop-shadow-[0_0_5px_rgba(168,85,247,0.5)]" />
                      <div>
                        <span className="font-bold text-purple-300 block mb-1">Gemini Rationale</span>
                        <span className="leading-relaxed text-white/80">{item.ai_reasoning}</span>
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>
              </motion.div>
            )
          })}

          {(!queue?.items || queue.items.length === 0) && (
            <motion.div
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              className="card py-20 text-center text-white/50 bg-dark-800/40 border border-white/5 flex flex-col items-center justify-center"
            >
              <div className="relative">
                <div className="absolute inset-0 bg-green-500/20 rounded-full blur-2xl" />
                <ClipboardCheck className="w-20 h-20 mb-6 text-green-400 relative z-10 drop-shadow-[0_0_15px_rgba(34,197,94,0.4)]" />
              </div>
              <h3 className="text-2xl font-black text-white mb-2">All Caught Up!</h3>
              <p className="text-base text-white/50 max-w-md mx-auto leading-relaxed">
                There are no pending validation items. Go to Products or Documents to enrich items and generate new validation proposals.
              </p>
            </motion.div>
          )}
        </div>
      </AnimatePresence>
    </motion.div>
  )
}
